services:
  db:
    image: gvenzl/oracle-free
    container_name: db_desafio_api
    hostname: app_db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: desafioApi
      APP_USER: desafio
      APP_USER_PASSWORD: desafioApi
    networks:
      - DESAFIO_SOFTDESIGN_NETWORK
    volumes:
      - DESAFIO_SOFTDESIGN_DATA_DB:/opt/oracle/oradata

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    container_name: rabbitmq_desafio_api
    hostname: "app-rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25676:25676"
    networks:
      - DESAFIO_SOFTDESIGN_NETWORK
    volumes:
      - DESAFIO_SOFTDESIGN_DATA_RABBITMQ:/var/lib/rabbitmq/mnesia/

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_api
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:oracle:thin:@db_desafio_api:1521/FREEPDB1
      RABBITMQ_HOST: rabbitmq_desafio_api
      FEIGN_CLIENT_USER_INFO_URL: http://cpf-mock:8080/
    networks:
      - DESAFIO_SOFTDESIGN_NETWORK
    depends_on:
      - db
      - rabbitmq
      - cpf-mock

  cpf-mock:
    image: wiremock/wiremock:latest
    container_name: cpf_mock_api
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    networks:
      - DESAFIO_SOFTDESIGN_NETWORK

volumes:
  DESAFIO_SOFTDESIGN_DATA_DB:
  DESAFIO_SOFTDESIGN_DATA_RABBITMQ:

networks:
  DESAFIO_SOFTDESIGN_NETWORK:
    driver: "bridge"
